project:
  type: website

website:
  title: "Data Burns"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blogs.qmd

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual

